name: genesis_pro
description: "Gênesis Pro — Fé, Criação e Resultados"
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_tts: ^3.8.5
  share_plus: ^7.2.1
  url_launcher: ^6.2.2

flutter:
  uses-material-design: true
